# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a44937b1dd33483cbfc34d70bfbb3a0fbb3b8f9654145364d7d9cbd241066b2f2c71e7af6ca3320a753677b953b03bd224a3079ee6e742af75640c36e7f0260

test:
  secret_key_base: ff230161311093609895f61dd8bc16265bb69953fb83c63442020595c167f1fe527cf2af04fd080bfc59c9509dbc448a774f5836b7bf0b560c6120188298f0a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
